# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PathoPatcher Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        python-version: 3.10.12
        environment-file: environment.yaml
        activate-environment: pathopatch_env
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
        auto-update-conda: true
        auto-activate-base: false
    - name : Run CLI Tests
      run: python -m pytest -vv -s ./tests/test_cli
    - name : Run Util Tests
      run: python -m pytest -vv -s ./tests/test_utils
    - name : Run Macenko Tests
      run: python -m pytest -vv -s ./tests/test_macenko_module
    - name : Run Core Tests
      run: python -m pytest -vv -s ./tests/test_core_modules
